### ISSUE TITLE
Admin Notification When Search Engines Are Blocked.

### ISSUE THREAD

**Issue by noameppel** [joeguilmette/wp-local-toolbox#19]
On a production website, WPLT_SERVER was set to 'CHICAGO'.

Since the server name was not 'PRODUCTION' or 'LIVE', search engines were prevented from indexing the website.

I think WP Local Toolbox needs a clearer way to notify and remind admins that search engines are blocked. Proposing adding a no index message to the WP Admin Bar:

![screenshot 2016-02-20 02 29 23](https://cloud.githubusercontent.com/assets/653153/13184969/c7c14026-d779-11e5-90d5-f94a6e01d356.png)

If that sounds good I can submit a Pull Request.

**Comment by jb510** [comment]
Joe - Personally I never liked the "default" actions here and how they worked either.  Might be worth a rethink.

Related - (NO INDEX) STAGING SERVER is probably ok in a 1600px wide browser... but I already get annoyed with STAGING SERVER taking up so much admin bar real estate, where I'm usully already running query monitor, debug objects, debub bar, jetpack stats, and more....   Icons and colors I think would work nicely.

**Comment by joeguilmette** [comment]
Fair enough. This plugin is the first original idea I really ever had,
code-wise. And it's the the first thing I 'made' that wasn't just for
practice.

I don't build sites for people anymore, so I don't really use the plugin
that much. It's an unbelievable honor that _anyone_ uses this, especially
since it's the first code that I ever pushed to GitHub and dotorg.

You guys can make whatever changes you want - Jon, your perms are such that
you can accept PRs, right?

**Comment by joeguilmette** [comment]
@jb510 we could ditch appending ' SERVER', and allow people to use Dashicons in addition to plain text for the server name - that would be cool... https://developer.wordpress.org/resource/dashicons/#admin-tools

Do we even need a dashboard icon to indicate indexing? If we make it manual then the user would need to go in there and manually set it in wp-config anyway.

**Comment by noameppel** [comment]
+1 for removing "SERVER".

Dashicons could be a good way to convey information without taking up too much valuable real estate in the wp admin bar.

Example: X could signify that search engines are blocked.

![screenshot 2016-02-20 19 50 10](https://cloud.githubusercontent.com/assets/653153/13196531/2f1a86e2-d80b-11e5-8c30-c08b09b36124.png)

Or a flag to indicate that it is a production environment.

![screenshot 2016-02-20 19 43 27](https://cloud.githubusercontent.com/assets/653153/13196496/4d583e48-d80a-11e5-8ff8-a9b065e47d3e.png)

**Comment by digiltd** [comment]
@cleanforestco Yes please!
I seemed to have missed that key bit of information when I first installed it. After many hours of trying to find out why I couldn't uncheck the "Discourage search engines from indexing this site" checkbox. 

I now know why :) 

So yes, some sort of indicator would be appreciated.

**Comment by joeguilmette** [comment]
That's perfect. Maybe we can also set it up so if you pass the dash icon ID
as the server name we can display that instead of a server name. And make
the search engine icon optional as well.

That would save a lot of space.

**Comment by joeguilmette** [comment]
We could even make the server name completely optional. Color would
probably be enough.

**Comment by joeguilmette** [comment]
- We treat blocking search engines like everything else. Disabled by default, can be enabled if you wanted it with a flag.
- Add a flag to force search engine visibility (can be true or false). If WPLT is doing anything in this regard we'll use a dashicon in the admin bar with an appropriate tooltip displayed on hover.
- Should add an admin notice on update so that people will know they have to go in and add a flag to wp-config to set their search engine visibility.
- Seems unanimous, remove `SERVER`

**Comment by joeguilmette** [comment]
https://github.com/joeguilmette/wp-local-toolbox/commit/3851148480204182b5d1619e376046bda74c33ca
